# Generated by Django 5.1.3 on 2024-12-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="indexdetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_title", models.CharField(max_length=50)),
                ("course_description", models.TextField(max_length=150)),
                ("course_thumbnail", models.ImageField(upload_to="thumbnails/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
