# Generated by Django 5.1.3 on 2024-12-05 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminWorkFlow", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("course_title", models.CharField(max_length=50)),
                ("course_description", models.TextField(max_length=150)),
                ("course_long_description", models.TextField(max_length=300)),
                ("course_price", models.FloatField(max_length=6)),
                (
                    "course_language",
                    models.CharField(
                        choices=[
                            ("English", "English"),
                            ("Hindi", "Hindi"),
                            ("Hinglish", "Hinglish"),
                        ],
                        default="English",
                        max_length=20,
                    ),
                ),
                ("course_duration", models.IntegerField(max_length=2)),
                ("course_startdata", models.DateField()),
                ("course_thumbnail", models.ImageField(upload_to="thumbnails/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name="indexdetails",
        ),
    ]
