# Generated by Django 5.1.3 on 2024-12-05 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminWorkFlow", "0002_coursedetails_delete_indexdetails"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursedetails",
            name="course_duration",
            field=models.IntegerField(),
        ),
    ]
