# Generated by Django 5.1.3 on 2024-12-06 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("AdminWorkFlow", "0005_remove_course_purchase_by_user_course_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="course_purchase_by_user",
            old_name="course_id",
            new_name="course",
        ),
    ]
