# Generated by Django 5.1.3 on 2024-12-06 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminWorkFlow", "0006_rename_course_id_course_purchase_by_user_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="Userquery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=25)),
                ("email", models.EmailField(max_length=254)),
                ("query_type", models.CharField(max_length=50)),
                ("query", models.TextField()),
                ("Date", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
