# Generated by Django 5.1.3 on 2024-12-07 14:47

import AdminWorkFlow.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminWorkFlow", "0007_userquery"),
    ]

    operations = [
        migrations.CreateModel(
            name="Add_Assignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "file",
                    models.FileField(
                        upload_to="assignments/",
                        validators=[AdminWorkFlow.models.validate_pdf],
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assignments",
                        to="AdminWorkFlow.coursedetails",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Add_Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "file",
                    models.FileField(
                        upload_to="videos/",
                        validators=[AdminWorkFlow.models.validate_video_file],
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="videos",
                        to="AdminWorkFlow.coursedetails",
                    ),
                ),
            ],
        ),
    ]
