# Generated by Django 5.1.3 on 2024-12-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminWorkFlow", "0009_assignment_submit"),
    ]

    operations = [
        migrations.AddField(
            model_name="add_assignment",
            name="marks",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="add_assignment",
            name="obtained_marks",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
