# Generated by Django 5.1.3 on 2024-12-12 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("AdminWorkFlow", "0010_add_assignment_marks_add_assignment_obtained_marks"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="add_assignment",
            name="obtained_marks",
        ),
        migrations.AddField(
            model_name="assignment_submit",
            name="obtained_marks",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
